### ISSUE TITLE
Segmentation fault when quickly trying to cancel a view operation

### ISSUE THREAD

**Issue by ctrlcctrlv** [ga2arch/slack#10]
It's possible to provoke a segmentation fault if you quickly try to change which window you are looking at.

To reproduce:

1. Select a channel with `<Enter>`
2. While channel loads, press `<Tab>`
3. Mash `<Up>` or `<Down>` as quickly as you can

It's also possible to trigger this bug, in my experience, just by getting unlucky and your first `<Up>` or `<Down>` triggers the segfault.

**Comment by ctrlcctrlv** [comment]
I may have confirmed that this bug _only_ occurs when musl is being used instead of glibc.

**Comment by FedeDP** [comment]
I cannot reproduce it here (glibc).

**Comment by ctrlcctrlv** [comment]
Good news!~ I went back to my libmusl box to try this again and this issue and #14 are one in the same! So this issue is also solved now. :)
