### ISSUE TITLE
Sometimes messages are broken while scrolling backwards

### ISSUE THREAD

**Issue by FedeDP** [ga2arch/slack#15]
Some messages gets broken while scrolling back in history; they appear correct if we scroll up enough to hide them, and then scroll down to show them again, so this is an UI issue (ie: no issue in SlackUI::add_history()).

It surely is Chat::draw() fault.

**Comment by FedeDP** [comment]
It seems fixed on my system. Some issues remains, though, eg:
*  ```triple backticks``` for code blocks
* Sometimes it seems to still lose some part of multilines messages.

**Comment by ctrlcctrlv** [comment]
I can't find any example of a message that looks right if I scroll it up off the screen and then scroll back down, so maybe this is fixed. Still many broken messages though (see comment in #16).
