### ISSUE TITLE
Page Up, Backspace, and other keys show up as special characters

### ISSUE THREAD

**Issue by ctrlcctrlv** [ga2arch/slack#8]
Backspace shows up as `ć`
Home shows up as `Ć`
Page up shows up as `œ`
Page down shows up as `Œ`
End shows up as `Ũ`

Weirdly, arrow keys and delete work.

![2017-10-20-173225_swaygrab](https://user-images.githubusercontent.com/838783/31814736-1d40d660-b5bd-11e7-9d6b-3045c48b5fd1.png)

**Comment by FedeDP** [comment]
SUPPORT:

- [x] PG_UP/DOWN in roster (go to first/last)
- [x] PG_UP/DOWN in Chat  (scroll an entire page)
- [x] support home and end in Input

EDIT: btw backspace is working for me.

**Comment by ctrlcctrlv** [comment]
~Commit https://github.com/ga2arch/slack/commit/9777707269182f8888689d3e4c8f91d92c5f62d1 strangely did not seem to work for me, I still get œ/Œ.~

~I know we're not using Python, but I feel this is relevant: https://stackoverflow.com/questions/22157426/getch-returns-wrong-characters~

Nevermind, looking at the commit again, I see that it is for the roster window, not chat window :)

**Comment by FedeDP** [comment]
Waiting for your PR then closing this issue :)

EDIT: obviously let me know if you encounter any issue!
